name: sos_cake
description: "A Flutter app to order cakes with same-day delivery (Ponyo aquarium theme)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:

  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.3


  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

  # API & HTTP
  http: ^1.2.2

  # Animations & Design
  animated_text_kit: ^4.2.2
  rive: ^0.13.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
