// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGiTbupLEjb1tcdqPVDuXP9mBek5-CeI',
    appId: '1:910095331565:web:bb01a049fc318233449ce4',
    messagingSenderId: '910095331565',
    projectId: 'flutter-auth-dfa2f',
    authDomain: 'flutter-auth-dfa2f.firebaseapp.com',
    storageBucket: 'flutter-auth-dfa2f.firebasestorage.app',
    measurementId: 'G-CMP0Q88ZZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAax9-YLMMpQIdSQZ4CQYcjG3RUyC63pEE',
    appId: '1:910095331565:android:1874efa6a6edc9ad449ce4',
    messagingSenderId: '910095331565',
    projectId: 'flutter-auth-dfa2f',
    storageBucket: 'flutter-auth-dfa2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBDNklR_NAP1TbG641A3Q2hjYSnBCa3I',
    appId: '1:910095331565:ios:580a624703693934449ce4',
    messagingSenderId: '910095331565',
    projectId: 'flutter-auth-dfa2f',
    storageBucket: 'flutter-auth-dfa2f.firebasestorage.app',
    iosBundleId: 'com.example.onboardingScreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBDNklR_NAP1TbG641A3Q2hjYSnBCa3I',
    appId: '1:910095331565:ios:580a624703693934449ce4',
    messagingSenderId: '910095331565',
    projectId: 'flutter-auth-dfa2f',
    storageBucket: 'flutter-auth-dfa2f.firebasestorage.app',
    iosBundleId: 'com.example.onboardingScreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGGiTbupLEjb1tcdqPVDuXP9mBek5-CeI',
    appId: '1:910095331565:web:457219c2f4a0366b449ce4',
    messagingSenderId: '910095331565',
    projectId: 'flutter-auth-dfa2f',
    authDomain: 'flutter-auth-dfa2f.firebaseapp.com',
    storageBucket: 'flutter-auth-dfa2f.firebasestorage.app',
    measurementId: 'G-K3HHCQW6YM',
  );
}
